spring:
  datasource:
    url: jdbc:mysql://192.168.43.94/selldb?characterEncoding=utf-8&useSSl=false
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8082
  context-path: /sell
